# CARRY exit rule 2026-09 (AUDIT + one policy decision)

Pre-registration: [README.md](README.md) (frozen before any run). Write-up: [findings.md](findings.md).
Five exit rules for S-078 on the full Binance settlement history, net of 0.24 % per toggle, with the C2 rule
simulator imported unchanged. Re-run: `run_p2_exit_rules.py`.

## Rules, per-year, era, tail stress, bootstrap, decision

In [1]:
%run run_p2_exit_rules.py

parity vs C2: {'got': {'LIVE': {'net_ann_pct': 10.845644985764642, 'rt_per_year': 4.750542299349241}, 'ALWAYS_ON': {'net_ann_pct': 11.693231101545555}}, 'expected': {'LIVE': {'net_ann_pct': 10.85, 'rt_per_year': 4.8}, 'ALWAYS_ON': {'net_ann_pct': 11.69}}, 'pass_': True}
rules over 2019-12-19..2026-09-11 (6.74 y):
                share_held  round_trips  rt_per_year  gross_ann_pct  net_ann_pct
LIVE                 0.906         32.0        4.751         11.796       10.846
ALWAYS_ON            1.000          1.0        0.148         11.723       11.693
SYMMETRIC_7D         0.898         32.0        4.751         11.875       10.924
LIVE_MINHOLD21       0.936         25.0        3.711         11.763       11.020
CUM30D               0.996          5.0        0.742         11.731       11.582
net %/yr by year:
 year             2020   2021  2022  2023   2024  2025  2026
rule
ALWAYS_ON       17.19  30.61  4.16  7.87  11.92  5.13  2.61
CUM30D          16.45  30.61  4.16  7.87  11.92  5.13  2.61
LIVE            16.32  30.08  2.49  7.24  11.53  4.51  1.56
LIVE_MINHOLD21  16.63  29.97  2.88  7.24  11.73  4.72  1.71
SYMMETRIC_7D    16.76  30.18  2.29  7.23  11.53  4.71  1.33
tail stress: {'worst_30d': {'cum_funding_pct': -1.311426, 'window': ['2020-03-12', '2020-04-10'], 'net_pct_in_window': {'LIVE': -1.297504, 'ALWAYS_ON': -1.311426, 'SYMMETRIC_7D': -0.8317970000000001, 'LIVE_MINHOLD21': -1.213342, 'CUM30D': -1.5474409999999998}}, 'worst_90d': {'cum_funding_pct': -0.3855839999999998, 'window': ['2026-02-06', '2026-05-06'], 'net_pct_in_window': {'LIVE': -0.768518, 'ALWAYS_ON': -0.38558399999999987, 'SYMMETRIC_7D': -0.93015, 'LIVE_MINHOLD21': -0.664828, 'CUM30D': -0.38558399999999987}}, 'worst_180d': {'cum_funding_pct': 0.529983, 'window': ['2025-12-31', '2026-06-28'], 'net_pct_in_window': {'LIVE': -0.2016079999999999, 'ALWAYS_ON': 0.529983, 'SYMMETRIC_7D': -0.3619479999999999, 'LIVE_MINHOLD21': -0.0979179999999999, 'CUM30D': 0.529983}}}

   ALWAYS_ON        diff vs LIVE  +0.85 %/yr  CI90 [ +0.60,  +1.11]  P(>0) 1.000
   SYMMETRIC_7D     diff vs LIVE  +0.08 %/yr  CI90 [ -0.11,  +0.27]  P(>0) 0.750
   LIVE_MINHOLD21   diff vs LIVE  +0.17 %/yr  CI90 [ +0.06,  +0.31]  P(>0) 0.995
   CUM30D           diff vs LIVE  +0.74 %/yr  CI90 [ +0.44,  +1.04]  P(>0) 1.000
decision: {'per_rule': {'ALWAYS_ON': {'beats_by_half_pct': True, 'ci_excludes_zero': True, 'worst_year_ok': True, 'worst_year': 2.61232655511811, 'live_worst_year': 1.5610245275590553, 'verdict': 'RECOMMEND'}, 'SYMMETRIC_7D': {'beats_by_half_pct': False, 'ci_excludes_zero': False, 'worst_year_ok': True, 'worst_year': 1.3306146850393703, 'live_worst_year': 1.5610245275590553, 'verdict': 'NO CHANGE'}, 'LIVE_MINHOLD21': {'beats_by_half_pct': False, 'ci_excludes_zero': True, 'worst_year_ok': True, 'worst_year': 1.710027874015748, 'live_worst_year': 1.5610245275590553, 'verdict': 'NO CHANGE'}, 'CUM30D': {'beats_by_half_pct': True, 'ci_excludes_zero': True, 'worst_year_ok': True, 'worst_year': 2.61232655511811, 'live_worst_year': 1.5610245275590553, 'verdict': 'RECOMMEND'}}, 'tail_insurance_premium_pct_per_year': -0.8475861157809135, 'verdict': 'RECOMMEND ALWAYS_ON, CUM30D'}

## Tables

In [2]:
import json, pandas as pd
pd.set_option('display.width', 220); pd.set_option('display.max_columns', 40)
R = json.load(open('results/p2_exit_rules.json', encoding='utf-8'))
print('parity:', R['parity'])
display(pd.DataFrame(R['rules']).T.round(3))
display(pd.read_csv('results/p2_per_year.csv').round(2))
print('era:', json.dumps(R['era'], indent=1)); print('tail stress:', json.dumps(R['tail_stress'], indent=1))
print('bootstrap vs LIVE:', json.dumps(R['bootstrap_vs_live'], indent=1)); print('decision:', json.dumps(R['decision'], indent=1))

parity: {'got': {'LIVE': {'net_ann_pct': 10.8456449858, 'rt_per_year': 4.7505422993}, 'ALWAYS_ON': {'net_ann_pct': 11.6932311015}}, 'expected': {'LIVE': {'net_ann_pct': 10.85, 'rt_per_year': 4.8}, 'ALWAYS_ON': {'net_ann_pct': 11.69}}, 'pass_': True}

                share_held  round_trips  rt_per_year  gross_ann_pct  net_ann_pct
LIVE                 0.906         32.0        4.751         11.796       10.846
ALWAYS_ON            1.000          1.0        0.148         11.723       11.693
SYMMETRIC_7D         0.898         32.0        4.751         11.875       10.924
LIVE_MINHOLD21       0.936         25.0        3.711         11.763       11.020
CUM30D               0.996          5.0        0.742         11.731       11.582

              rule  year     n  share_held  round_trips  net_ann_pct
0             LIVE  2020  1098        0.87            6        16.32
1             LIVE  2021  1095        0.94            3        30.08
2             LIVE  2022  1095        0.89            8         2.49
3             LIVE  2023  1095        0.98            3         7.24
4             LIVE  2024  1098        0.95            2        11.53
5             LIVE  2025  1095        0.94            3         4.51
6             LIVE  2026   762        0.74            5         1.56
7        ALWAYS_ON  2020  1098        1.00            0        17.19
8        ALWAYS_ON  2021  1095        1.00            0        30.61
9        ALWAYS_ON  2022  1095        1.00            0         4.16
10       ALWAYS_ON  2023  1095        1.00            0         7.87
11       ALWAYS_ON  2024  1098        1.00            0        11.92
12       ALWAYS_ON  2025  1095        1.00            0         5.13
13       ALWAYS_ON  2026   762        1.00            0         2.61
14    SYMMETRIC_7D  2020  1098        0.86            6        16.76
15    SYMMETRIC_7D  2021  1095        0.92            3        30.18
16    SYMMETRIC_7D  2022  1095        0.88            9         2.29
17    SYMMETRIC_7D  2023  1095        0.98            3         7.23
18    SYMMETRIC_7D  2024  1098        0.95            2        11.53
19    SYMMETRIC_7D  2025  1095        0.95            2         4.71
20    SYMMETRIC_7D  2026   762        0.70            6         1.33
21  LIVE_MINHOLD21  2020  1098        0.91            4        16.63
22  LIVE_MINHOLD21  2021  1095        0.95            3        29.97
23  LIVE_MINHOLD21  2022  1095        0.92            6         2.88
24  LIVE_MINHOLD21  2023  1095        0.98            3         7.24
25  LIVE_MINHOLD21  2024  1098        0.97            1        11.73
26  LIVE_MINHOLD21  2025  1095        0.96            2         4.72
27  LIVE_MINHOLD21  2026   762        0.81            4         1.71
28          CUM30D  2020  1098        0.97            4        16.45
29          CUM30D  2021  1095        1.00            0        30.61
30          CUM30D  2022  1095        1.00            0         4.16
31          CUM30D  2023  1095        1.00            0         7.87
32          CUM30D  2024  1098        1.00            0        11.92
33          CUM30D  2025  1095        1.00            0         5.13
34          CUM30D  2026   762        1.00            0         2.61

era: {
 "LIVE": {
  "pre_etf": {
   "net_ann_pct": 13.8762166446,
   "round_trips": 22
  },
  "post_etf": {
   "net_ann_pct": 6.2339956,
   "round_trips": 10
  }
 },
 "ALWAYS_ON": {
  "pre_etf": {
   "net_ann_pct": 14.8533551842,
   "round_trips": 1
  },
  "post_etf": {
   "net_ann_pct": 6.8844405744,
   "round_trips": 0
  }
 },
 "SYMMETRIC_7D": {
  "pre_etf": {
   "net_ann_pct": 13.9986972287,
   "round_trips": 22
  },
  "post_etf": {
   "net_ann_pct": 6.2464359231,
   "round_trips": 10
  }
 },
 "LIVE_MINHOLD21": {
  "pre_etf": {
   "net_ann_pct": 14.0416703819,
   "round_trips": 18
  },
  "post_etf": {
   "net_ann_pct": 6.4229907282,
   "round_trips": 7
  }
 },
 "CUM30D": {
  "pre_etf": {
   "net_ann_pct": 14.6691782015,
   "round_trips": 5
  },
  "post_etf": {
   "net_ann_pct": 6.8844405744,
   "round_trips": 0
  }
 }
}
tail stress: {
 "worst_30d": {
  "cum_funding_pct": -1.311426,
  "window": [
   "2020-03-12",
   "2020-04-10"
  ],
  "net_pct_in_window": {
   "LIVE": -1.297504,
   "ALWAYS_ON": -1.311426,
   "SYMMETRIC_7D": -0.831797,
   "LIVE_MINHOLD21": -1.213342,
   "CUM30D": -1.547441
  }
 },
 "worst_90d": {
  "cum_funding_pct": -0.385584,
  "window": [
   "2026-02-06",
   "2026-05-06"
  ],
  "net_pct_in_window": {
   "LIVE": -0.768518,
   "ALWAYS_ON": -0.385584,
   "SYMMETRIC_7D": -0.93015,
   "LIVE_MINHOLD21": -0.664828,
   "CUM30D": -0.385584
  }
 },
 "worst_180d": {
  "cum_funding_pct": 0.529983,
  "window": [
   "2025-12-31",
   "2026-06-28"
  ],
  "net_pct_in_window": {
   "LIVE": -0.201608,
   "ALWAYS_ON": 0.529983,
   "SYMMETRIC_7D": -0.361948,
   "LIVE_MINHOLD21": -0.097918,
   "CUM30D": 0.529983
  }
 }
}
bootstrap vs LIVE: {
 "ALWAYS_ON": {
  "diff_ann_pct": 0.8475861158,
  "ci90_ann_pct": [
   0.5956681533,
   1.1140783783
  ],
  "p_gt_0": 1.0
 },
 "SYMMETRIC_7D": {
  "diff_ann_pct": 0.0788434145,
  "ci90_ann_pct": [
   -0.1056640113,
   0.26961734
  ],
  "p_gt_0": 0.7504
 },
 "LIVE_MINHOLD21": {
  "diff_ann_pct": 0.1747892265,
  "ci90_ann_pct": [
   0.055762103,
   0.3124672092
  ],
  "p_gt_0": 0.9946
 },
 "CUM30D": {
  "diff_ann_pct": 0.7364456941,
  "ci90_ann_pct": [
   0.4380791411,
   1.0399898484
  ],
  "p_gt_0": 1.0
 }
}
decision: {
 "per_rule": {
  "ALWAYS_ON": {
   "beats_by_half_pct": true,
   "ci_excludes_zero": true,
   "worst_year_ok": true,
   "worst_year": 2.6123265551,
   "live_worst_year": 1.5610245276,
   "verdict": "RECOMMEND"
  },
  "SYMMETRIC_7D": {
   "beats_by_half_pct": false,
   "ci_excludes_zero": false,
   "worst_year_ok": true,
   "worst_year": 1.330614685,
   "live_worst_year": 1.5610245276,
   "verdict": "NO CHANGE"
  },
  "LIVE_MINHOLD21": {
   "beats_by_half_pct": false,
   "ci_excludes_zero": true,
   "worst_year_ok": true,
   "worst_year": 1.710027874,
   "live_worst_year": 1.5610245276,
   "verdict": "NO CHANGE"
  },
  "CUM30D": {
   "beats_by_half_pct": true,
   "ci_excludes_zero": true,
   "worst_year_ok": true,
   "worst_year": 2.6123265551,
   "live_worst_year": 1.5610245276,
   "verdict": "RECOMMEND"
  }
 },
 "tail_insurance_premium_pct_per_year": -0.8475861158,
 "verdict": "RECOMMEND ALWAYS_ON, CUM30D"
}