# ADX robustness pack 2026-09 (AUDIT + one policy decision)

Pre-registration: [README.md](README.md) (frozen before any run). Write-up: [findings.md](findings.md).

| id | question |
|---|---|
| (a) | the shipped Tier-2 configuration under the harness fill model vs live semantics (1 m stops, next-day trail, 15 bp, funding) |
| (b)(c) | 24 day boundaries: MTM drawdown, sizing off it; phase ensembles k = 2, 3, 24 |
| (d) | late entry h hours after the boundary |
| (e) | funding paid by longs; overlap with CARRY's perp short |

## (a) live semantics

In [1]:
%run run_p1a_live_semantics.py

parity (harness T2, study window): {'n': 27, 'ret_pct': 2483.2414339232196, 'max_dd': -15.12349381412768, 'mar': 3.090501705801238} -> PASS
port check: harness entries 22 port signals 22 harness entries missing from port: []
harness fill (10 bp): {'n': 21, 'mean_net_pct': 16.069351697026953, 'reasons': {'ADX<20': 12, 'ATR_trail': 5, 'SL': 4}, 'ret_pct': 941.9819082358221, 'max_dd_tradeclose': -15.12349381412767, 'mar_tradeclose': 2.7720833180523137} {'cagr_pct': 43.00579517062806, 'mtm_maxdd_pct': -38.00450635375739, 'sharpe': 1.188797099156123, 'mar': 1.1315972577124713, 'days': 2446, 'total_pct': 997.4117361705339}

live semantics (15 bp + funding): {'n': 21, 'mean_net_pct': 14.459981156496216, 'win': 0.5714285714285714, 'worst_pct': -10.601103433837057, 'sum_net_pct': 303.6596042864205, 'reasons': {'ADX<20': 12, 'ATR_trail': 6, 'SL': 3}, 'funding_pct_sum': -34.808629, 'median_init_stop_pct': 10.0} {'cagr_pct': 35.959093985404245, 'mtm_maxdd_pct': -48.069243137263356, 'sharpe': 1.0170444611775098, 'mar': 0.7480686534364985, 'days': 2400, 'total_pct': 652.6699809389253}
live semantics, no funding: {'cagr_pct': 44.18238565194776, 'mtm_maxdd_pct': -38.35345627856725, 'sharpe': 1.2048057651662025, 'mar': 1.151979246173906, 'days': 2400, 'total_pct': 1007.1003477879874}
gap (live - harness 10bp): {'cagr_pct': -7.046701185223817, 'mtm_maxdd_pct': -10.064736783505964, 'sharpe': -0.17175263797861318, 'mar': -0.3835286042759728}

## (b)(c) phases, sizing, ensembles

In [2]:
%run run_p1bc_phases.py

phase  0: n=21 mean +14.46% CAGR 36.0% MTM maxDD -48.1% Sharpe 1.02 MAR 0.75
phase  1: n=19 mean +15.49% CAGR 33.1% MTM maxDD -41.7% Sharpe 0.99 MAR 0.79

phase  2: n=19 mean +15.25% CAGR 38.2% MTM maxDD -41.6% Sharpe 1.06 MAR 0.92

phase  3: n=22 mean +14.29% CAGR 44.0% MTM maxDD -41.6% Sharpe 1.09 MAR 1.06

phase  4: n=20 mean +14.34% CAGR 40.6% MTM maxDD -36.0% Sharpe 1.12 MAR 1.13

phase  5: n=21 mean +11.99% CAGR 28.3% MTM maxDD -37.6% Sharpe 0.86 MAR 0.75

phase  6: n=22 mean +10.98% CAGR 27.0% MTM maxDD -37.7% Sharpe 0.84 MAR 0.71

phase  7: n=24 mean +11.21% CAGR 28.1% MTM maxDD -44.7% Sharpe 0.81 MAR 0.63

phase  8: n=25 mean +11.78% CAGR 31.7% MTM maxDD -38.5% Sharpe 0.87 MAR 0.82

phase  9: n=23 mean +11.67% CAGR 28.5% MTM maxDD -43.9% Sharpe 0.83 MAR 0.65

phase 10: n=22 mean +11.20% CAGR 25.7% MTM maxDD -44.0% Sharpe 0.82 MAR 0.58

phase 11: n=21 mean +12.50% CAGR 29.0% MTM maxDD -47.8% Sharpe 0.87 MAR 0.61

phase 12: n=19 mean +13.59% CAGR 26.7% MTM maxDD -40.4% Sharpe 0.83 MAR 0.66

phase 13: n=23 mean +12.94% CAGR 35.7% MTM maxDD -36.8% Sharpe 0.95 MAR 0.97

phase 14: n=24 mean +11.57% CAGR 30.2% MTM maxDD -41.0% Sharpe 0.85 MAR 0.74

phase 15: n=23 mean +9.80% CAGR 22.8% MTM maxDD -38.6% Sharpe 0.74 MAR 0.59

phase 16: n=23 mean +9.37% CAGR 21.6% MTM maxDD -40.9% Sharpe 0.71 MAR 0.53

phase 17: n=23 mean +9.26% CAGR 21.7% MTM maxDD -37.9% Sharpe 0.72 MAR 0.57

phase 18: n=22 mean +9.28% CAGR 19.5% MTM maxDD -38.8% Sharpe 0.69 MAR 0.50

phase 19: n=22 mean +10.22% CAGR 20.2% MTM maxDD -49.9% Sharpe 0.67 MAR 0.40

phase 20: n=25 mean +9.33% CAGR 18.2% MTM maxDD -47.5% Sharpe 0.63 MAR 0.38

phase 21: n=23 mean +11.51% CAGR 28.1% MTM maxDD -45.9% Sharpe 0.81 MAR 0.61

phase 22: n=25 mean +10.77% CAGR 24.4% MTM maxDD -49.9% Sharpe 0.75 MAR 0.49

phase 23: n=25 mean +12.32% CAGR 35.9% MTM maxDD -49.0% Sharpe 0.99 MAR 0.73
sizing: {'dd_budget_pct': 25.0, 'worst_phase_mtm_maxdd_pct': -49.90332702962834, 'median_phase_mtm_maxdd_pct': -41.56178227606308, 'median_initial_stop_pct': 10.0, 'shipped_notional_x_typical': 0.2, 'shipped_account_maxdd_worst_phase_pct': -9.98066540592567, 'shipped_account_maxdd_live_phase_pct': -9.613848627452672, 'notional_x_for_budget_worst_phase': 0.5009686024572496, 'notional_x_for_budget_median_phase': 0.601514146673118, 'risk_pct_for_budget_worst_phase': 5.009686024572496}

k2_0_12 {'phases': [0, 12], 'cagr_pct': 32.243, 'mtm_maxdd_pct': -38.252, 'sharpe': 1.025, 'mar': 0.843, 'days': 2400, 'total_pct': 527.373, 'rule': {'maxdd_5pp_better_than_median': False, 'sharpe_ge_median': True, 'k_le_3': True}, 'verdict': 'NO CHANGE'} dSharpe {'point': 0.008414553546148618, 'ci': [-0.21153459509992592, 0.004106865101851598, 0.24668675165798154], 'p_gt_0': 0.511, 'block': 30, 'n_iter': 2000} dMAR {'point': 0.0947846563643262, 'ci': [-0.45558320996854196, 0.033984881387753595, 0.5301947563586953], 'p_gt_0': 0.5625, 'block': 30, 'n_iter': 2000}

k3_0_8_16 {'phases': [0, 8, 16], 'cagr_pct': 29.128, 'mtm_maxdd_pct': -36.758, 'sharpe': 0.926, 'mar': 0.792, 'days': 2400, 'total_pct': 436.401, 'rule': {'maxdd_5pp_better_than_median': False, 'sharpe_ge_median': True, 'k_le_3': True}, 'verdict': 'NO CHANGE'} dSharpe {'point': -0.09106292747343381, 'ci': [-0.33880622573858543, -0.09688366445419316, 0.16781433597598702], 'p_gt_0': 0.2625, 'block': 30, 'n_iter': 2000} dMAR {'point': 0.044318858285691154, 'ci': [-0.6649922637342747, -0.09707478025111524, 0.3541426453786574], 'p_gt_0': 0.325, 'block': 30, 'n_iter': 2000}

k24_all {'phases': [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23], 'cagr_pct': 27.852, 'mtm_maxdd_pct': -34.504, 'sharpe': 0.932, 'mar': 0.807, 'days': 2400, 'total_pct': 402.519, 'rule': {'maxdd_5pp_better_than_median': True, 'sharpe_ge_median': True, 'k_le_3': False}, 'verdict': 'NO CHANGE'} dSharpe {'point': -0.08523579402242809, 'ci': [-0.40103403632093604, -0.09226863309746175, 0.22273689152714624], 'p_gt_0': 0.301, 'block': 30, 'n_iter': 2000} dMAR {'point': 0.059114661330511686, 'ci': [-0.7216610401021762, -0.07796691515758064, 0.4437847858187102], 'p_gt_0': 0.3785, 'block': 30, 'n_iter': 2000}

## (d) late entry

In [3]:
%run run_p1d_late_entry.py

same trades, late entry price:
         n  missed  mean_net_pct  delta_vs_h0
h0   21.0     0.0        14.460        0.000
h1   21.0     0.0        14.218       -0.242
h2   21.0     0.0        14.177       -0.283
h6   21.0     0.0        13.979       -0.481
h12  21.0     0.0        13.743       -0.717
h23  21.0     0.0        13.851       -0.609

machine re-run with delayed entry tick:
         n  mean_net_pct  cagr_pct  mtm_maxdd_pct  sharpe    mar    days  total_pct
h0   21.0        14.460    35.959        -48.069   1.017  0.748  2400.0    652.670
h1   21.0        14.178    35.001        -47.655   0.999  0.734  2400.0    618.499
h2   21.0        14.142    34.667        -47.719   0.992  0.726  2400.0    606.897
h6   21.0        13.985    34.318        -47.458   0.987  0.723  2400.0    594.947
h12  21.0        13.814    33.880        -47.162   0.979  0.718  2400.0    580.171
h23  21.0        13.769    33.893        -45.374   0.979  0.747  2400.0    580.633
decision: {'delta_6h_pp': -0.4813840090437669, 'within_half_pp': True, 'verdict': 'current behaviour fine; document the assumption'}

## (e) funding and venue

In [4]:
%run run_p1e_funding.py

{'n': 14, 'funding_paid_pct_sum': 37.41243000000001, 'per_trade_mean_pct': 2.672316428571429, 'long_days': 553.8902777777778, 'pct_per_year_of_long_exposure': 24.67075268467231, 'share_trades_paying': 1.0, 'max_paid_pct': 9.311775}
{'n': 7, 'funding_received_pct_sum': 2.603801}
{'long_days': 563, 'share_carry_on': 0.9662522202486679, 'carry_on_share_all_days': 0.9007424775302852, 'note': "when CARRY's perp short is on, the pair's perp legs net and the ADX long is economically a spot long"}
{'spot_extra_fee_bp_rt': 10.0, 'funding_paid_bp_per_trade_mean': 267.2316428571429, 'longs_where_spot_cheaper': 12}

## Tables

In [5]:
import json, pandas as pd
pd.set_option('display.width', 220); pd.set_option('display.max_columns', 40)
A = json.load(open('results/p1a_live_semantics.json', encoding='utf-8'))
print('parity:', A['parity']); print('port check:', A['port_check'])
print('harness fill:', json.dumps(A['harness_fill'], indent=1)); print('live:', json.dumps(A['live'], indent=1)); print('gap:', A['gap'])
B = json.load(open('results/p1bc_phases.json', encoding='utf-8'))
display(pd.read_csv('results/p1b_phases.csv').round(3)); print('ranges [min, median, max]:', B['phase_ranges']); print('sizing:', B['sizing'])
for k, v in B['ensembles'].items(): print(k, {kk: vv for kk, vv in v.items()})
D = json.load(open('results/p1d_late_entry.json', encoding='utf-8'))
display(pd.DataFrame(D['by_delay']).T.round(3)); display(pd.DataFrame(D['machine_with_delay']).T.round(3)); print(D['decision'])
E = json.load(open('results/p1e_funding.json', encoding='utf-8')); print(json.dumps(E, indent=1))

parity: {'got': {'n': 27, 'ret_pct': 2483.2414339232196, 'max_dd': -15.12349381412768, 'mar': 3.090501705801238}, 'expected': {'n': 27, 'ret_pct': 2483, 'max_dd': -15.1, 'mar': 3.09}, 'pass_': True}
port check: {'n_harness_entries': 22, 'n_port_signals': 22, 'harness_not_in_port': []}
harness fill: {
 "ledger": {
  "n": 21,
  "mean_net_pct": 16.069351697026953,
  "reasons": {
   "ADX<20": 12,
   "ATR_trail": 5,
   "SL": 4
  },
  "ret_pct": 941.9819082358221,
  "max_dd_tradeclose": -15.12349381412767,
  "mar_tradeclose": 2.7720833180523137
 },
 "curve_10bp": {
  "cagr_pct": 43.00579517062806,
  "mtm_maxdd_pct": -38.00450635375739,
  "sharpe": 1.188797099156123,
  "mar": 1.1315972577124713,
  "days": 2446,
  "total_pct": 997.4117361705339
 },
 "curve_15bp": {
  "cagr_pct": 42.777678810757976,
  "mtm_maxdd_pct": -38.10209316424301,
  "sharpe": 1.1840890217765994,
  "mar": 1.1227120417337801,
  "days": 2446,
  "total_pct": 985.7418720458153
 }
}
live: {
 "ledger": {
  "n": 21,
  "mean_net_pct": 14.459981156496216,
  "win": 0.5714285714285714,
  "worst_pct": -10.601103433837057,
  "sum_net_pct": 303.6596042864205,
  "reasons": {
   "ADX<20": 12,
   "ATR_trail": 6,
   "SL": 3
  },
  "funding_pct_sum": -34.808629,
  "median_init_stop_pct": 10.0
 },
 "curve": {
  "cagr_pct": 35.959093985404245,
  "mtm_maxdd_pct": -48.069243137263356,
  "sharpe": 1.0170444611775098,
  "mar": 0.7480686534364985,
  "days": 2400,
  "total_pct": 652.6699809389253
 }
}
gap: {'cagr_pct': -7.046701185223817, 'mtm_maxdd_pct': -10.064736783505964, 'sharpe': -0.17175263797861318, 'mar': -0.3835286042759728}

    phase_hour   n  mean_net_pct  worst_pct  median_init_stop_pct  cagr_pct  mtm_maxdd_pct  sharpe    mar  days  total_pct
0            0  21        14.460    -10.601                  10.0    35.959        -48.069   1.017  0.748  2400    652.670
1            1  19        15.490    -10.084                  10.0    33.061        -41.708   0.991  0.793  2398    552.290
2            2  19        15.248    -10.725                  10.0    38.159        -41.556   1.056  0.918  2098    540.232
3            3  22        14.292    -10.895                  10.0    43.960        -41.568   1.091  1.058  1989    627.308
4            4  20        14.341    -10.146                  10.0    40.551        -35.962   1.125  1.128  1989    538.319
5            5  21        11.988    -10.146                  10.0    28.300        -37.557   0.861  0.754  2097    318.172
6            6  22        10.979    -10.146                  10.0    26.959        -37.737   0.835  0.714  2097    293.697
7            7  24        11.208    -10.170                  10.0    28.067        -44.690   0.807  0.628  2097    313.831
8            8  25        11.783    -10.575                  10.0    31.726        -38.491   0.871  0.824  2170    414.027
9            9  23        11.666    -12.923                  10.0    28.473        -43.902   0.828  0.649  2168    342.448
10          10  22        11.202    -10.138                  10.0    25.693        -44.027   0.819  0.584  2167    288.333
11          11  21        12.502    -10.259                  10.0    29.034        -47.809   0.872  0.607  2169    354.365
12          12  19        13.594    -10.127                  10.0    26.739        -40.365   0.828  0.662  2255    331.874
13          13  23        12.942    -10.035                  10.0    35.674        -36.835   0.946  0.968  2168    511.570
14          14  24        11.567    -10.164                  10.0    30.181        -40.976   0.847  0.737  2146    370.985
15          15  23         9.800    -10.510                  10.0    22.752        -38.640   0.743  0.589  2266    256.728
16          16  23         9.370    -17.931                  10.0    21.588        -40.932   0.711  0.527  2097    207.165
17          17  23         9.264    -10.541                  10.0    21.724        -37.866   0.720  0.574  1988    191.534
18          18  22         9.281    -10.204                  10.0    19.492        -38.835   0.686  0.502  2096    177.855
19          19  22        10.223    -11.019                  10.0    20.196        -49.903   0.667  0.405  2096    187.373
20          20  25         9.326    -10.224                  10.0    18.157        -47.502   0.631  0.382  2395    198.624
21          21  23        11.514    -10.403                  10.0    28.072        -45.925   0.811  0.611  2097    313.918
22          22  25        10.767    -12.625                  10.0    24.425        -49.883   0.751  0.490  2375    314.119
23          23  25        12.320    -11.510                  10.0    35.878        -48.980   0.989  0.733  2398    648.475

ranges [min, median, max]: {'cagr_pct': [18.156895802189045, 28.18565889874651, 43.95994947748103], 'mtm_maxdd_pct': [-49.90332702962834, -41.56178227606308, -35.961913113709166], 'sharpe': [0.6309624348978273, 0.8317688532739173, 1.124526984625848], 'mar': [0.382236892726029, 0.6554905161973177, 1.1276016453736712], 'n': [19.0, 22.5, 25.0]}
sizing: {'dd_budget_pct': 25.0, 'worst_phase_mtm_maxdd_pct': -49.90332702962834, 'median_phase_mtm_maxdd_pct': -41.56178227606308, 'median_initial_stop_pct': 10.0, 'shipped_notional_x_typical': 0.2, 'shipped_account_maxdd_worst_phase_pct': -9.98066540592567, 'shipped_account_maxdd_live_phase_pct': -9.613848627452672, 'notional_x_for_budget_worst_phase': 0.5009686024572496, 'notional_x_for_budget_median_phase': 0.601514146673118, 'risk_pct_for_budget_worst_phase': 5.009686024572496}
k2_0_12 {'phases': [0, 12], 'cagr_pct': 32.24323687228596, 'mtm_maxdd_pct': -38.25183789610216, 'sharpe': 1.0254590147236584, 'mar': 0.8429199391637997, 'days': 2400, 'total_pct': 527.3730892154323, 'delta_sharpe_vs_phase0': {'point': 0.008414553546148618, 'ci': [-0.21153459509992592, 0.004106865101851598, 0.24668675165798154], 'p_gt_0': 0.511, 'block': 30, 'n_iter': 2000}, 'delta_mar_vs_phase0': {'point': 0.0947846563643262, 'ci': [-0.45558320996854196, 0.033984881387753595, 0.5301947563586953], 'p_gt_0': 0.5625, 'block': 30, 'n_iter': 2000}, 'rule': {'maxdd_5pp_better_than_median': False, 'sharpe_ge_median': True, 'k_le_3': True}, 'verdict': 'NO CHANGE'}
k3_0_8_16 {'phases': [0, 8, 16], 'cagr_pct': 29.127638228810483, 'mtm_maxdd_pct': -36.75840898317178, 'sharpe': 0.925981533704076, 'mar': 0.7924074799359594, 'days': 2400, 'total_pct': 436.40110132852294, 'delta_sharpe_vs_phase0': {'point': -0.09106292747343381, 'ci': [-0.33880622573858543, -0.09688366445419316, 0.16781433597598702], 'p_gt_0': 0.2625, 'block': 30, 'n_iter': 2000}, 'delta_mar_vs_phase0': {'point': 0.044318858285691154, 'ci': [-0.6649922637342747, -0.09707478025111524, 0.3541426453786574], 'p_gt_0': 0.325, 'block': 30, 'n_iter': 2000}, 'rule': {'maxdd_5pp_better_than_median': False, 'sharpe_ge_median': True, 'k_le_3': True}, 'verdict': 'NO CHANGE'}
k24_all {'phases': [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23], 'cagr_pct': 27.85174119862379, 'mtm_maxdd_pct': -34.5036350399092, 'sharpe': 0.9318086671550817, 'mar': 0.8072117956965582, 'days': 2400, 'total_pct': 402.51902216859656, 'delta_sharpe_vs_phase0': {'point': -0.08523579402242809, 'ci': [-0.40103403632093604, -0.09226863309746175, 0.22273689152714624], 'p_gt_0': 0.301, 'block': 30, 'n_iter': 2000}, 'delta_mar_vs_phase0': {'point': 0.059114661330511686, 'ci': [-0.7216610401021762, -0.07796691515758064, 0.4437847858187102], 'p_gt_0': 0.3785, 'block': 30, 'n_iter': 2000}, 'rule': {'maxdd_5pp_better_than_median': True, 'sharpe_ge_median': True, 'k_le_3': False}, 'verdict': 'NO CHANGE'}

        n  missed  mean_net_pct  delta_vs_h0
h0   21.0     0.0        14.460        0.000
h1   21.0     0.0        14.218       -0.242
h2   21.0     0.0        14.177       -0.283
h6   21.0     0.0        13.979       -0.481
h12  21.0     0.0        13.743       -0.717
h23  21.0     0.0        13.851       -0.609

        n  mean_net_pct  cagr_pct  mtm_maxdd_pct  sharpe    mar    days  total_pct
h0   21.0        14.460    35.959        -48.069   1.017  0.748  2400.0    652.670
h1   21.0        14.178    35.001        -47.655   0.999  0.734  2400.0    618.499
h2   21.0        14.142    34.667        -47.719   0.992  0.726  2400.0    606.897
h6   21.0        13.985    34.318        -47.458   0.987  0.723  2400.0    594.947
h12  21.0        13.814    33.880        -47.162   0.979  0.718  2400.0    580.171
h23  21.0        13.769    33.893        -45.374   0.979  0.747  2400.0    580.633

{'delta_6h_pp': -0.4813840090437669, 'within_half_pp': True, 'verdict': 'current behaviour fine; document the assumption'}
{
 "env": {
  "python": "3.13.11",
  "numpy": "2.4.4",
  "pandas": "3.0.2",
  "run_at": "2026-09-12T05:55:00+00:00"
 },
 "longs": {
  "n": 14,
  "funding_paid_pct_sum": 37.41243000000001,
  "per_trade_mean_pct": 2.672316428571429,
  "long_days": 553.8902777777778,
  "pct_per_year_of_long_exposure": 24.67075268467231,
  "share_trades_paying": 1.0,
  "max_paid_pct": 9.311775
 },
 "shorts": {
  "n": 7,
  "funding_received_pct_sum": 2.603801
 },
 "netting": {
  "long_days": 563,
  "share_carry_on": 0.9662522202486679,
  "carry_on_share_all_days": 0.9007424775302852,
  "note": "when CARRY's perp short is on, the pair's perp legs net and the ADX long is economically a spot long"
 },
 "venue_arith": {
  "spot_extra_fee_bp_rt": 10.0,
  "funding_paid_bp_per_trade_mean": 267.2316428571429,
  "longs_where_spot_cheaper": 12
 }
}